# hyper_config.yaml
lr:
  - 1e-5
  - 5e-5
batch_size:
  - 8
  - 16
dropout_rate:
  - 0.1
  - 0.5
weight_decay:
  - 1e-5
  - 1e-2
warmup_steps:
  - 0
  - 500
max_len:
  - 128
  - 512
optimizer_name:
  - 'AdamW'
num_classes: 5